# Generated by Django 5.0.5 on 2024-05-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='createt_by',
            new_name='created_by',
        ),
    ]
